version: '3'

env:
  PROJECT_NAME: mcore
  UID:
    sh: echo "$(id -u)"
  GID:
    sh: echo "$(id -g)"
  PHP_VERSION:
    sh: echo "${PHP_VERSION}"

tasks:
  build:
    cmds:
      - docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME build --compress --pull --no-cache --force-rm
  down:
    cmds:
      - docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME down
  clear:
    cmds:
      - docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME down --rmi all
  composer:
    cmds:
      - docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME run --rm php composer {{.CLI_ARGS}}
  install:
    cmds:
      - task: composer
        vars: {CLI_ARGS: 'install'}
  update:
    cmds:
      - task: composer
        vars: {CLI_ARGS: 'update'}
  dump:
    cmds:
      - task: composer
        vars: {CLI_ARGS: 'dump'}
  analyse:
    cmds:
      - task: composer
        vars: {CLI_ARGS: 'analyse'}
  test:
    cmds:
      - task: composer
        vars: {CLI_ARGS: 'test'}