version: '3.8'
services:
  php:
    container_name: mcore_php
    environment:
      - XDEBUG_MODE=coverage
      - PHP_IDE_CONFIG=serverName=mcore
    image: mcore_php
    build:
      context: "."
      dockerfile: "php/Dockerfile"
      args:
        UID: ${UID}
        GID: ${GID}
    networks:
      - docker
    volumes:
      - ../:/app
      - ~/.config/composer/auth.json:/home/app/.composer/auth.json
      - ~/.ssh/:/home/app/.ssh:ro
networks:
  docker:
    name: docker