version: '3.8'
services:
  php:
    environment:
      - XDEBUG_MODE=develop,coverage
    build:
      context: "."
      dockerfile: "php/Dockerfile"
      args:
        UID: ${UID}
        GID: ${GID}
    networks:
      - docker
    volumes:
      - ../:/app
networks:
  docker:
    name: docker